### ISSUE TITLE
add old TFS feactures

### ISSUE THREAD

**Issue by 397821** [tryller/crystalserver#7]
<-- TFS 0.3 -->

	cleanProtectedZones (DONE)
	globalSaveEnabled = "no" - CODED IN LUA
	teleportPlayerSummons = "yes" (DONE)						
	removeWeaponAmmunition = "no" (DONE)
	removeWeaponCharges = "no" (DONE)
	displayOnOrOffAtCharlist = "no" (DONE)  thanks frcento					
	premiumPlayerSkipWaitList = "yes" (DONE)				
	bedsRequirePremium = "yes" (DONE)

	-- sem prioridade  --para ots noob
	Account manager
	ingameGuildManagement

**Comment by tryller** [comment]
Implemented removeWeaponCharges it's used for two configs removeWeaponAmmunition and removeWeaponCharges (enable and disbale two)

https://github.com/tryller/crystalserver/commit/c0cdcd3e08cc83d7f1162cc070e6659c8486aff3
